### ISSUE TITLE
Problem with language mapping in case of duplicated percentage

### ISSUE THREAD

**Issue by christiand93** [generaltso/linguist#3]
Hi,

I noticed, that if two languages have exactly the same byte-count, the result output is wrong. Both percentages gets mapped to the same language.

To test it, I created a css and a js file. Both have the same file size. Here is the output from the tool:
```
JavaScript: 50.0000%
JavaScript: 50.0000%
```

I think the problem is, that existing entries in the qqq map get overwritten, if percentage is the same:

```go
// From cmd/l/main.go starting at line 188
...
results := []float64{}
qqq := map[float64]string{}
for lang, num := range langs {
	res := (float64(num) / float64(total_size)) * 100.0
	results = append(results, res)
	qqq[res] = lang  // <-- overwriting map entries, if percentage already existing
}
...
```

Kind regards,
Christian

**Comment by generaltso** [comment]
Nice catch, thanks for this :D
